name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # https://srz-zumix.blogspot.com/2019/10/github-actions-ci-skip.html
  prepare:
      runs-on: ubuntu-latest
      if: "! contains(github.event.head_commit.message, '[skip ci]')"
      steps:
        - run: echo "[skip ci] ${{ contains(github.event.head_commit.message, '[skip ci]') }}"
        - run: echo "[github.ref] ${{ github.ref }}"

  build:
    needs: ["prepare"]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build docs
        run: npm run docs:build

      - name: Publish to npm
        if: github.ref == 'refs/tags/*'
        run: npm publish

      - name: Deploy docs
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist
